### ISSUE TITLE
core.mjs:7739 ERROR Error: Ajax error for SafeValue must use

### ISSUE THREAD

**Issue by nicoesiea** [mengshukeji/Luckyexcel#86]
When I try to use LuckyExcel.transformExcelToLuckyByUrl 
I get this error:
````
core.mjs:7739 ERROR Error: Ajax error for SafeValue must use [property]=binding: SafeValue must use [property]=binding: /[...]/download/[...] (see https://g.co/ng/security#xss) (see https://g.co/ng/security#xss) : 400 
    at xhr.onreadystatechange [as __zone_symbol__ON_PROPERTYreadystatechange] (luckyexcel.umd.js:22726:18)
    at XMLHttpRequest.wrapFn (zone.js:766:39)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25681:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
    at invokeTask (zone.js:1661:18)
    at globalCallback (zone.js:1692:29)
    at XMLHttpRequest.globalZoneAwareCallback (zone.js:1725:16)
````

Is there a solution for this?
I tried to replace my URL by :
````this.sanitizer.bypassSecurityTrustHtml(this.downloadUrl.toString()),````
But it is the same result

**Comment by nicoesiea** [comment]
For now, the solution I found is to not use the security mode, and only call the URL by passing the String value... not clean, but working !
